// <auto-generated />
using System;
using DSPA_MeAudVis.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DSPA_MeAudVis.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200910163855_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CAdministrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CBecario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UsuarioId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Becarios");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CManual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CUsuarioId");

                    b.Property<string>("Contenido")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CUsuarioId");

                    b.ToTable("Manuales");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CPrestamoId");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Marca")
                        .HasMaxLength(15);

                    b.Property<string>("Modelo")
                        .HasMaxLength(15);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("NumSerie")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("CPrestamoId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado");

                    b.Property<DateTime>("FechaHoraEntrega");

                    b.Property<DateTime>("FechaHoraSalida");

                    b.Property<int?>("becarioEntregaId");

                    b.Property<int>("becarioSalidaId");

                    b.Property<int>("solicitanteId");

                    b.HasKey("Id");

                    b.HasIndex("becarioEntregaId");

                    b.HasIndex("becarioSalidaId");

                    b.HasIndex("solicitanteId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CSolicitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deudor");

                    b.Property<string>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Solicitantes");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CUsuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<int>("Matricula")
                        .HasMaxLength(8);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("TipoDeUsuario")
                        .IsRequired();

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CAdministrador", b =>
                {
                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CBecario", b =>
                {
                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CManual", b =>
                {
                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CUsuario")
                        .WithMany("Manuales")
                        .HasForeignKey("CUsuarioId");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CMaterial", b =>
                {
                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CPrestamo")
                        .WithMany("Materiales")
                        .HasForeignKey("CPrestamoId");
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CPrestamo", b =>
                {
                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CBecario", "becarioEntrega")
                        .WithMany()
                        .HasForeignKey("becarioEntregaId");

                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CBecario", "becarioSalida")
                        .WithMany()
                        .HasForeignKey("becarioSalidaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CSolicitante", "solicitante")
                        .WithMany()
                        .HasForeignKey("solicitanteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DSPA_MeAudVis.Web.Data.Entities.CSolicitante", b =>
                {
                    b.HasOne("DSPA_MeAudVis.Web.Data.Entities.CUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
